using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using TodoAppMVVM.Views;
using Caliburn.Micro;
using TodoAppMVVM.SQLite;
using TodoAppMVVM.Models;
using TodoAppMVVM.Queries;
using System.IO;
using TodoAppMVVM.Services;
using System.Windows;
using Prism.Commands;
using System.ComponentModel;
using Hangfire.Annotations;
using System.Runtime.CompilerServices;

namespace TodoAppMVVM.ViewModels
{
    public class MainViewModel //:  INotifyPropertyChanged
    {
        //#region Variables
        //public Visibility LblInvisibleTextVisibility
        //{
        //    get => _lblInvisibleTextVisibility;
        //    set
        //    {
        //        OnPropertyChanged(nameof(LblInvisibleTextVisibility)); //we are notifying the view that this property has been set, therefore the visibility has changed
        //        _lblInvisibleTextVisibility = value;
        //    }
        //}
        //public Visibility Btn_CreateListVisibility
        //{
        //    get => _btn_CreateListVisibility;
        //    set
        //    {
        //        OnPropertyChanged(nameof(Btn_CreateListVisibility)); //we are notifying the view that this property has been set, therefore the visibility has changed
        //        _btn_CreateListVisibility = value;
        //    }
        //}
        //private Visibility _lblInvisibleTextVisibility; //sub property used for holding values within the above monitored variable
        //private Visibility _btn_CreateListVisibility; //sub property used for holding values within the above monitored variable
        //#endregion

        //#region Constructor
        private bool _btn_CreateListVisibility;
        public bool Btn_CreateListVisibility
        {
            get { return _btn_CreateListVisibility; }
            private set
            {
                _btn_CreateListVisibility = value;
                OnPropertyChanged("Btn_CreateListVisibility");
            }
        }
        public MainViewModel()
        {
            if (File.Exists("TodoDatabase.db"))
            { }
            else
            {
                createDb.CreateDb();
            }
            //ItemQuery = _ItemQuery;
            //TodoQuery = _TodoQuery;
            //unitofWork = _unitofWork;
            //_dbConnect = dbConnect;
            unitofWork = new UnitOfWork();
            _dbConnect = new BuildConnection();
            //DbConnect db = new DbConnect();
            GetList();
            
            //LblInvisibleTextVisibility = Visibility.Hidden; //reset initial value
            //Btn_CreateListVisibility = Visibility.Visible;
            //BtnToggleLblVisibilityDelegateCommand = new DelegateCommand(ToggleVisibility); //implement this method now, this delegate command will call this when started!
        }
        //#endregion
        //#region Delegate Commands
        //public DelegateCommand BtnToggleLblVisibilityDelegateCommand { get; set; } //set the function this button push will call in constructor above even
        //#endregion
        //#region Delegate Command Functions
        //private void ToggleVisibility() //no parameters are allowed for this type of delegate command, however it is possible, i will attempt to do another vid on it
        //{
        //    if (LblInvisibleTextVisibility == Visibility.Visible) //if visible
        //    {
        //        LblInvisibleTextVisibility = Visibility.Hidden; //hide it
        //    }
        //    else //if hidden
        //    {
        //        LblInvisibleTextVisibility = Visibility.Visible; //show it
        //    }
        //    //=============
        //    //if (Btn_CreateListVisibility == Visibility.Visible) //if visible
        //    //{
        //    //    Btn_CreateListVisibility = Visibility.Hidden; //hide it
        //    //}
        //    //else //if hidden
        //    //{
        //    //    Btn_CreateListVisibility = Visibility.Visible; //show it
        //    //}
        //    //with any luck, the button is bound to the 'BtnToggleLblVisibilityDelegateCommand' command, and the command calls THIS function, thus updateing the visibility of the label
        //    //LETS SEEEE
        //}
        //#endregion
        //#region Property Changed Logic -- autogenerated
        ///* Property changed logic -- notifies the view when something has changed that we are watching, for example the LblInvisibleTextVisibility property */
        //public event PropertyChangedEventHandler PropertyChanged;
        //[NotifyPropertyChangedInvocator]
        //protected virtual void OnPropertyChanged([CallerMemberName] string propertyName = null)
        //{
        //    PropertyChanged?.Invoke(this, new PropertyChangedEventArgs(propertyName));
        //}
        #endregion
        //========================================================================================================
        IWindowManager manager = new WindowManager();
        //private IObservableCollection<TodoModel> todoModel ;
        public BindableCollection<TodoModel> listDataGrid { get; set; }
        public BindableCollection<ItemModel> itemsDataGrid { get; set; }

        //private readonly IBuildConnection _dbConnect;

        //private readonly IUnitOfWork unitofWork;

        private readonly BuildConnection _dbConnect;

        private readonly UnitOfWork unitofWork;

        private readonly DBContext createDb = new DBContext();
        //public MainViewModel()//IBuildConnection dbConnect, IUnitOfWork _unitofWork)//IGetAllTodoQuery _TodoQuery, IGetAllItemQuery _ItemQuery
        //{
        //    if (File.Exists("TodoDatabase.db"))
        //    { }
        //    else
        //    {
        //        createDb.CreateDb();
        //    }
        //    //ItemQuery = _ItemQuery;
        //    //TodoQuery = _TodoQuery;
        //    //unitofWork = _unitofWork;
        //    //_dbConnect = dbConnect;
        //    unitofWork = new UnitOfWork();
        //    _dbConnect = new BuildConnection();
        //    //DbConnect db = new DbConnect();
        //    GetList();
            
        //}
        private void GetList()
        {

            //var container = App.Configure();
            //var _listDbContext = container.Resolve<IDetalistRepository>();
            //var _itemDbContext = container.Resolve<IItemRepository>();

            listDataGrid = new BindableCollection<TodoModel>(unitofWork.ListServices.LoadList());
            itemsDataGrid = new BindableCollection<ItemModel>(unitofWork.ItemServices.LoadItem(1));

            //itemsDataGrid.ItemsSource = _itemDbContext.GetAll(ListDataId);
            listDataGrid.Refresh();
            itemsDataGrid.Refresh();
            // bind to the source

        }
        public void Btn_CreateList() // Open Windows to Add Item Todo Data
        {
            //CreateTodoView viewCtodo = new CreateTodoView();
            //viewCtodo.ShowDialog();
            //DisplayRootViewFor<CreateTodoViewModel>();

            //Bootstrapper _container = new Bootstrapper();

            //var TodoWindow = _container.GetInstance(CreateTodoViewModel, CreateTodoViewModel);
            //var updateDataList = new TodoModel
            //{
            //    TodoModelId = 1,
            //    Name = "passname",
            //    Description = ""
            //};
            //----------
            //DisplayRootViewFor<MainViewModel>();
            Btn_CreateListVisibility = Visibility.Hidden; //show it
            CreateTodoViewModel TodoWindow = new CreateTodoViewModel();

            manager.ShowDialog(TodoWindow);
            //--------
            GetList();
            //manager.ShowWindow(new CreateTodoViewModel(), null, null);

            //MessageView viewCtodo = new MessageView();
            //viewCtodo.ShowDialog();

        }
       
        //private string msg = "this is message";
        //public string Labelmsg
        //{
        //    get { return msg; }
        //    set { msg = value; }
        //}
        
        public void Btn_ViewItem()
        {

            CreateTodoViewModel TodoWindow = new CreateTodoViewModel();

            manager.ShowDialog(TodoWindow);
            //Btn_CreateList.Visibility = Visibility.Hidden;
            //btn_CreateItem.Visibility = Visibility.Visible;
            //btn_BacktoListView.Visibility = Visibility.Visible;

            //listDataGrid.Visibility = Visibility.Hidden;
            //itemsDataGrid.Visibility = Visibility.Visible;
        }

        //============================================================ delete
        private DelegateCommand<TodoModel> _deleteCommand;
        public DelegateCommand<TodoModel> DeleteCommand =>
                    _deleteCommand ?? (_deleteCommand = new DelegateCommand<TodoModel> (ExecuteDeleteCommand));
        void ExecuteDeleteCommand(TodoModel parameter)
        {
            //MessageViewModel msg = new MessageViewModel();
            //msg.Message = parameter.TodoModelId.ToString();

            //manager.ShowWindow(msg);
            var result = unitofWork.catchResult(unitofWork.ListServices.RemoveList(parameter));
            MessageBox.Show(result);
            GetList();
            //parameter.TodoModelId
            //https://www.youtube.com/watch?v=IRE2PAD1kIM
        }
        //========================================================== Edit Commnad
        private DelegateCommand<TodoModel> _editCommand;
        public DelegateCommand<TodoModel> EditCommand =>
                    _editCommand ?? (_editCommand = new DelegateCommand<TodoModel>(ExecuteEditCommand));
        void ExecuteEditCommand(TodoModel parameter)
        {
         
            CreateTodoViewModel TodoWindow = new CreateTodoViewModel();
            
            TodoWindow.Id = parameter.TodoModelId;
            TodoWindow.Name = parameter.Name;
            TodoWindow.Description = parameter.Description;

            manager.ShowDialog(TodoWindow);

            
            GetList();
        }

    }
    
}
